services:
  server:
    build: .
    profiles: ["frontend"]
    ports:
      - "3002:3002"
    command: node ./bin/server.js --no-colors
    env_file:
      - .env
      - .env.docker
    depends_on:
      init:
        condition: service_completed_successfully
  worker:
    build: .
    profiles: ["worker"]
    command: node ./bin/worker.js --no-colors
    env_file:
      - .env
      - .env.docker
    depends_on:
      init:
        condition: service_completed_successfully
  valkey:
    image: valkey/valkey:alpine
    profiles: ["db"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:16-alpine
    profiles: ["db"]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: yhub
      POSTGRES_PASSWORD: yhub
      POSTGRES_DB: yhub
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yhub"]
      interval: 5s
      timeout: 5s
      retries: 5
  s3mock:
    image: adobe/s3mock:latest
    profiles: ["db"]
    ports:
      - 9090:9090
    environment:
      - initialBuckets=yhub,yhub-testing
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9090"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
  init:
    build: .
    profiles: ["db"]
    command: sh -c "sleep 5 && node ./bin/init-db.js ; echo done"
    env_file:
      - .env
      - .env.docker
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
      s3mock:
        condition: service_healthy
