services:
  server:
    build: .
    profiles: ["frontend"]
    ports:
      - "3002:3002"
    command: node ./bin/server.js --no-colors
    env_file:
      - .env
      - .env.docker
    depends_on:
      init:
        condition: service_completed_successfully
  worker:
    build: .
    profiles: ["worker"]
    command: node ./bin/worker.js --no-colors
    env_file:
      - .env
      - .env.docker
    depends_on:
      init:
        condition: service_completed_successfully
  redis:
    image: redis:alpine
    profiles: ["db"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:16-alpine
    profiles: ["db"]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: yhub
      POSTGRES_PASSWORD: yhub
      POSTGRES_DB: yhub
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yhub"]
      interval: 5s
      timeout: 5s
      retries: 5
  minio:
    image: quay.io/minio/minio
    profiles: ["db"]
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address :9001
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
  init:
    build: .
    profiles: ["db"]
    command: sh -c "sleep 5 && node ./bin/init-db.js ; echo done"
    env_file:
      - .env
      - .env.docker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
